version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  backend:
    build: .
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:zaheer3260@localhost:5432/pollvoting
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - .:/usr/src/main
